// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMUzyRyCScJgsE2Nhj5UH9J_A4S_nc_HE',
    appId: '1:850265360907:web:8fc276cc087f8bae8ad50e',
    messagingSenderId: '850265360907',
    projectId: 'postfaym',
    authDomain: 'postfaym.firebaseapp.com',
    storageBucket: 'postfaym.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuOlBAHM0lsTveKtfyewvQezxZtxlo3C4',
    appId: '1:850265360907:android:6c20b4752d5ae4df8ad50e',
    messagingSenderId: '850265360907',
    projectId: 'postfaym',
    storageBucket: 'postfaym.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADIWvHbLpu-cInAWAPQFUCVFljUu_HfW0',
    appId: '1:850265360907:ios:1592d69f1fa2474f8ad50e',
    messagingSenderId: '850265360907',
    projectId: 'postfaym',
    storageBucket: 'postfaym.appspot.com',
    iosClientId: '850265360907-ddqaq0q805nof0kttj4t43vre40rmri8.apps.googleusercontent.com',
    iosBundleId: 'com.example.postfaymTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADIWvHbLpu-cInAWAPQFUCVFljUu_HfW0',
    appId: '1:850265360907:ios:31bc3c6134ef8cd18ad50e',
    messagingSenderId: '850265360907',
    projectId: 'postfaym',
    storageBucket: 'postfaym.appspot.com',
    iosClientId: '850265360907-nh7o4d88ulv355dg548ftso6tcrhgbdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.postfaymTask.RunnerTests',
  );
}
